### ISSUE TITLE
readScratchData does not return correct values

### ISSUE THREAD

**Issue by duffek** [PunchThrough/bean-sdk-android#22]
Using this Arduino code to set scratch:
Bean.setScratchNumber(5, 500);

Using iOS code to read:
    -(void) bean:(PTDBean *)bean didUpdateScratchNumber:(NSNumber *)number withValue:(NSData     *)data {
        if ([number intValue] == 5)  {
            // decode the value
            NSInteger decodedInteger;
            [data getBytes:&decodedInteger length:sizeof(decodedInteger)];
       }
    }
This results in:
2016-01-06 16:54:31.005 PetTutorBlu[2145:905176] scratch bank: 5 - decoded integer is: 500

On Android I use:
    bean.readScratchData(ScratchBank.BANK_5, new Callback<ScratchData>() {
       @Override
       public void onResult(ScratchData result) {
          Log.d("Bean", "Scratch bank 5 for connected bean is: " + result);
        }
    });

This results in:
D/Bean: Scratch bank 5 for connected bean is: ScratchData{number=5, data=[-12, 1, 0, 0]} 

I would have expected the result to be:
data=[500, 0, 0, 0]} 

I also thought I was thinking about this incorrectly and had to covert ByteArray to int which also failed:
    public static int byteArrayToInt(byte[] b) {
        final ByteBuffer bb = ByteBuffer.wrap(b);
        bb.order(ByteOrder.LITTLE_ENDIAN);
        return bb.getInt();
    }

Looks like there might be an inconsistency on how iOS and Arduino read/writes scratch memory and how Android does.

Thanks,
-David

**Comment by swstack** [comment]
Hi @duffek,

There has recently been a fix related to reading scratch characteristics in the SDK:

Issue - #17 
PR - #16 

A new version of the SDK (v1.0.2) has since been released to [Maven Central Repository](http://search.maven.org/#artifactdetails%7Ccom.punchthrough.bean.sdk%7Csdk%7C1.0.2%7Caar). Could you please ensure that you are running the latest version of the SDK in your app and retest? I believe this should clear up the issue.

Thanks!
