### ISSUE TITLE
onDiscoveryComplete callback never fires on Galaxy S5 Marshmallow

### ISSUE THREAD

**Issue by NeoSkye** [PunchThrough/bean-sdk-android#28]
On a Samsung Galaxy S5 running Android 6.0.1, the onDiscoveryComplete() callback won't fire if a bean is within range. onBeanDiscovered() will fire over and over again, about every 0.5 seconds.

This appears to be a problem in the bean-sdk-android in the BeanManager's LeScanCallback where the timeout on the onDiscoveryComplete() gets reset every time a bean is discovered, regardless of whether it is new or not.

**Comment by swstack** [comment]
@NeoSkye 

Thanks for making this issue public knowledge, rather than it just living inside of my head and our internal bug tracker. I appreciate your pull request SO MUCH, always love to have collaboration.

Anyway, I just cut `v2.1.0` of the SDK, and it is already publicly available on Maven Central! Go ahead and update your `build.gradle` and test it out. I updated our README to show off the new API:

```
BeanManager.getInstance().setScanTimeout(15);  // Timeout in seconds, optional, default is 30 seconds
BeanManager.getInstance().startDiscovery(listener);
```

Let me know how this works for you!
